### ISSUE TITLE
Simulation not working

### ISSUE THREAD

**Issue by Magnido9** [BNN-UPC/BNNetSimulator#1]
Hey,

I am trying to use your simulation with the new docker,
the notebook you posted here uses the older docker from the competition which is still limited to 10 nodes.
when trying to use the new docker I got the following error:
![image](https://user-images.githubusercontent.com/40192962/235699794-d0124caa-e21b-4295-8bd9-b1f1c72e4247.png)
while it worked with the older simulation.

Best regards,
ido

**Comment by albert-lopez** [comment]
Thanks to notifying us this error. The commit f1a9e8274602d300f9d50b26a3f7b894a61c9449 solve this issue.
